default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  packages: !include_dir_named packages

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 365
  commit_interval: 60
  exclude:
    entity_globs:
      - sensor.browser_*

sun:

sensor:
  - platform: time_date
    display_options:
      - time
      - date

# when reinstalling, remember to unlink/link the automation from the Google Home App (on phone)
# coert / xf64n3EmCdmYYYe1
google_assistant:
  project_id: !secret google_project_id
  service_account: !include service_account.json
  report_state: true
  expose_by_default: false

http:
  server_port: 8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.1.1
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  ip_ban_enabled: true
  login_attempts_threshold: 10

# Text to speech
tts:
  - platform: google_translate

notify:
  - platform: group
    name: all_devices
    services:
      - action: mobile_app_coert_s_phone
      - action: mobile_app_pixel_6

frontend:
  themes: !include_dir_merge_named themes/
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js

lovelace:
  mode: storage
  dashboards:
    lovelace-ui:
      mode: yaml
      title: "Dashboard"
      icon: mdi:script
      show_in_sidebar: true
      filename: lovelace.yaml
    simple-ui:
      mode: yaml
      title: "Dashboard"
      icon: mdi:script
      show_in_sidebar: true
      filename: simple.yaml
    simple2-ui:
      mode: yaml
      title: "Dashboard"
      icon: mdi:script
      show_in_sidebar: true
      filename: simple2.yaml

logger:
  default: warning
  logs:
    custom_components.cable_modem_monitor: debug
