homeassistant:
  customize:
    sensor.los_altos_country_club_aqi:
      friendly_name: "Air Quality Index"
      icon: mdi:waves
    sensor.los_altos_country_club_humidity:
      friendly_name: "Air Humidity"
      icon: mdi:water-percent
    sensor.los_altos_country_club_pm1:
      friendly_name: "Air Particles ≤ 1 µm"
      icon: mdi:waves
    sensor.los_altos_country_club_pm2_5:
      friendly_name: "Air Particles ≤ 2.5 µm"
      icon: mdi:waves
    sensor.los_altos_country_club_pm10:
      friendly_name: "Air Particles ≤ 10 µm"
      icon: mdi:waves
    sensor.los_altos_country_club_pressure:
      friendly_name: "Air Pressure"
      icon: mdi:arrow-collapse-down
    sensor.los_altos_country_club_temperature:
      friendly_name: "Air Temperature"
      icon: mdi:thermometer
    sensor.los_altos_country_club_volatile_organic_compounds_air_quality_index:
      friendly_name: "Air VOC AQI"
      icon: mdi:waves
#sensor:
#- unique_id: opnpool_min_air_temperature
#  name: "OPNpool min air temperature"
#  platform: statistics
#  state_characteristic: value_min
#  entity_id: sensor.opnpool_air_temp
#  max_age:
#    hours: 24

#- unique_id: opnpool_max_air_temperature
#  name: "OPNpool max air temperature"
#  platform: statistics
#  state_characteristic: value_max
#  entity_id: sensor.opnpool_air_temp
#  max_age:
#    hours: 24

