# Similar to electric power, entities that directly represent Total Energy are
# named "_energy", except for devices that are grouped together.  These
# individual devices are named ending "etl" (Energy TotaL).  E.g. the energy
# of a light ends in "_lightetl".

# so that Energy Config recognizes these as energy sensors
# prevent: "The unit of measurement `kWh` is not valid together with device class `power` when processing MQTT discovery message topic"

# Error 'The unit of measurement `kWh` is not valid together with
# device class  `power`' when processing MQTT discovery message
# topic: homeassistant/sensor/A977C1_ENERGY_Total/config',
# message: '{
#   'availability_topic': 'sonoff/s31-12/tele/LWT',
#   'name': 'sonoff-s31-12 ENERGY Total',
#   'device_class': 'power',
#   'state_topic': 'sonoff/s31-12/tele/SENSOR',
#   'force_update': True,
#   'value_template': "{{value_json['ENERGY']['Total']}}",
#   'unit_of_measurement': 'kWh',
#   'payload_available': 'Online',
#   'payload_not_available': 'Offline',
#   'unique_id': 'A977C1_ENERGY_Total',
#   'device': {'identifiers': ['A977C1']}
# }'

homeassistant:
  customize_glob:
    sensor.sonoff*_energy:
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing
      #last_reset: "1970-01-01T00:00:00+00:00"
    sensor.sonoff*_etl:
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing

sensor:
  # energy = power integrated over time

  - unique_id: dryer_energy
    name: "Dryer Energy"
    platform: integration
    source: sensor.electric_meter_dryer_power
    unit_prefix: k
    round: 2
    max_sub_interval:
      minutes: 5

  - unique_id: upstairs_hallway_cooling_hvac_ene
    name: "Upstairs Hallway Cooling HVAC ene"
    platform: integration
    source: sensor.upstairs_hallway_cooling_hvac_pwr
    unit_prefix: k
    round: 2
    max_sub_interval:
      minutes: 5

  - unique_id: estimated_idle_energy
    name: "Estimated Idle Energy"
    platform: integration
    source: sensor.estimated_idle_power
    unit_prefix: k
    round: 2
    max_sub_interval:
      minutes: 5

  - unique_id: opnpool_pump_energy
    name: "OPNpool Pump Energy"
    platform: integration
    source: sensor.opnpool_pump_power
    unit_prefix: k
    round: 2
    max_sub_interval:
      minutes: 5

template:
  - sensor:
      # total house energy (read from PG&E using Eagle 200)

      - unique_id: total_energy
        name: "Total Energy"
        device_class: energy
        unit_of_measurement: kWh
        state_class: total_increasing
        state: >-
          {% set value = states('sensor.eagle_200_total_meter_energy_delivered') %}
          {% if value != 'unavailable' and value != 'unknown' %}
          {{    value | float }}
          {% else %}
          {{     value }}
          {% endif %}

      # group individual devices together (each entity ends in "etl")

      - unique_id: light_energy # from the Leviton switches/dimmers
        name: "Light Energy"
        device_class: energy
        unit_of_measurement: "kWh"
        state_class: total_increasing
        state: >-
          {{
              states.sensor | 
              selectattr('entity_id', 'match', 'sensor\..*_light_daily_ene') |
              map(attribute='state') | 
              map('float', 0) | sum
          }}

      - unique_id: computer_energy # from the sonoff/tamota
        name: "Computer Energy"
        device_class: energy
        unit_of_measurement: "kWh"
        state_class: total_increasing
        state: >-
          {{
              states.sensor | 
              selectattr('entity_id', 'match', 'sensor\..*_computer_daily_ene') |
              map(attribute='state') | 
              map('float', 0) | sum
          }}

      - unique_id: hvac_energy
        name: "HVAC Energy"
        device_class: energy
        unit_of_measurement: "kWh"
        state_class: total_increasing
        state: >-
          {{
              states.sensor | 
              selectattr('entity_id', 'match', 'sensor\..*_hvac.*_ene') |
              map(attribute='state') | 
              map('float', 0) | sum
          }}

      - unique_id: fridge_energy # from the sonoff/tamota
        name: "Fridge Energy"
        device_class: energy
        unit_of_measurement: "kWh"
        state_class: total_increasing
        state: >-
          {{
              states.sensor | 
              selectattr('entity_id', 'match', 'sensor\..*_fridg_daily_ene') |
              map(attribute='state') | 
              map('float', 0) | sum
          }}
