# Similar to electric power, entities that directly represent Total Energy are
# named "_energy", except for devices that are grouped together.  These
# individual devices are named ending "etl" (Energy TotaL).  E.g. the energy
# of a light ends in "_lightetl".

sensor:
  # energy = power integrated over time

  - unique_id: dryer_energy
    name: "Dryer energy"
    platform: integration
    source: sensor.electric_meter_dryer_power
    unit_prefix: k
    round: 2
    max_sub_interval:
      minutes: 5

  - unique_id: upstairs_hallway_cooling_hvac_ene
    name: "Upstairs hallway cooling HVAC ene"
    platform: integration
    source: sensor.upstairs_hallway_cooling_hvac_pwr
    unit_prefix: k
    round: 2
    max_sub_interval:
      minutes: 5

  - unique_id: estimated_idle_energy
    name: "Estimated idle energy"
    platform: integration
    source: sensor.estimated_idle_power
    unit_prefix: k
    round: 2
    max_sub_interval:
      minutes: 5

  - unique_id: opnpool_pump_energy
    name: "OPNpool pump energy"
    platform: integration
    source: sensor.opnpool_pump_power
    unit_prefix: k
    round: 2
    max_sub_interval:
      minutes: 5

template:
  - sensor:
      # total house energy (read from PG&E using Eagle 200)

      - unique_id: total_energy
        name: "Total energy"
        device_class: energy
        unit_of_measurement: kWh
        state_class: total_increasing
        state: >-
          {% set value = states('sensor.eagle_200_total_meter_energy_delivered') %}
          {% if value != 'unavailable' and value != 'unknown' %}
          {{    value | float }}
          {% else %}
          {{     value }}
          {% endif %}

      # group individual devices together (each entity ends in "etl")

      - unique_id: light_energy # from the Leviton switches/dimmers
        name: "Light energy"
        device_class: energy
        unit_of_measurement: "kWh"
        state_class: total_increasing
        state: >-
          {{
              states.sensor | 
              selectattr('entity_id', 'match', 'sensor\..*_light_daily_ene') |
              map(attribute='state') | 
              map('float', 0) | sum
          }}

      - unique_id: computer_energy # from the sonoff/tamota
        name: "Computer energy"
        device_class: energy
        unit_of_measurement: "kWh"
        state_class: total_increasing
        state: >-
          {{
              states.sensor | 
              selectattr('entity_id', 'match', 'sensor\..*_computer_daily_ene') |
              map(attribute='state') | 
              map('float', 0) | sum
          }}

      - unique_id: hvac_energy
        name: "HVAC energy"
        device_class: energy
        unit_of_measurement: "kWh"
        state_class: total_increasing
        state: >-
          {{
              states.sensor | 
              selectattr('entity_id', 'match', 'sensor\..*_hvac.*_ene') |
              map(attribute='state') | 
              map('float', 0) | sum
          }}

      - unique_id: fridge_energy # from the sonoff/tamota
        name: "Fridge energy"
        device_class: energy
        unit_of_measurement: "kWh"
        state_class: total_increasing
        state: >-
          {{
              states.sensor | 
              selectattr('entity_id', 'match', 'sensor\..*_fridg_daily_ene') |
              map(attribute='state') | 
              map('float', 0) | sum
          }}
