media_player:
  - platform: emby
    host: !secret emby_host
    api_key: !secret emby_api_key

homeassistant:
  customize:
    media_player.apartment_tv:
      friendly_name: "Tv\u00B2"
      device_class: tv
    media_player.family_room_tv:
      friendly_name: "Tv\u00B2"
      device_class: tv

#script:
#  samsung_tv_energy_saving:
#    alias: "Eco mode"
#    icon: mdi:leaf
#    sequence:
#      - action: browser_mod.notification
#        data:
#          duration: 8000
#          message: Setting eco mode on TV in bedroom...
#      - action: media_player.play_media
#        target:
#          entity_id: media_player.samsung
#        data:
#          media_content_type: send_key
#          media_content_id: >
#            {% set sequence = [
#              'KEY_MENU', '1600',
#              'KEY_DOWN', '400',
#              'KEY_DOWN', '400',
#              'KEY_DOWN', '400',
#              'KEY_ENTER', '900',
#              'KEY_DOWN', '400',
#              'KEY_DOWN', '400',
#              'KEY_DOWN', '400',
#              'KEY_ENTER', '900',
#              'KEY_ENTER', '400',
#              'KEY_DOWN', '400',
#              'KEY_DOWN', '400',
#              'KEY_ENTER', '400',
#              'KEY_HOME', '400',
#              'KEY_HOME'
#            ] %}
#
#            {{ sequence | join('+') }}

#  bedroom_tv_night:
#    alias: "Night mode"
#    icon: mdi:bed
#    sequence:
#      - action: media_player.volume_set
#        data:
#          volume_level: 0.1
#        target:
#          entity_id: media_player.samsung
#      - action: light.turn_off
#        data:
#          transition: 10
#        target:
#          area_id: bedroom
#      - action: script.samsung_tv_energy_saving

template:
  - select:
      - name: conditional_media
        state: >
          {% set recently_added = 'Last added' %}
          {% set paused_timeout_minutes = 15 %}
          {% set media_players = [
            states.media_player.vardagsrum,
            states.media_player.sovrum,
            states.media_player.spotify ] %}

          {% macro media(state) %}
          {% set state = media_players | selectattr('state','eq',state) | list %}
          {% set last_changed = recently_added if state | length == 0 else state | map(attribute='last_changed') | list | max %}
            {{ state | selectattr('last_changed','eq', last_changed) | map(attribute='name') | list | join }}
          {% endmacro %}

          {% set playing = media_players | selectattr('state','eq','playing') | list %}
          {% set timeout_playing = False if playing | length == 0 else
            (as_timestamp(now()) - as_timestamp(playing | map(attribute='last_changed') | list | max)) < paused_timeout_minutes * 60 %}

          {% set paused = media_players | selectattr('state','eq','paused') | list %}
          {% set timeout_paused = False if paused | length == 0 else
            (as_timestamp(now()) - as_timestamp(paused | map(attribute='last_changed') | list | max)) < paused_timeout_minutes * 60 %}

          {% if playing %}
            {{ media('playing') if timeout_playing else media('paused') if timeout_paused else media('playing') }}
          {% elif paused %}
            {{ media('paused') if timeout_paused else recently_added }}
          {% else %}
            {{ recently_added }}
          {% endif %}
        options: >
          {% set recently_added = ['Senast tillagt'] %}
          {% set media_players = [
            states.media_player.vardagsrum,
            states.media_player.sovrum,
            states.media_player.spotify ] %}
          {{ recently_added + media_players | map(attribute='name') | list }}
        select_option:
          action: select.select_option
          target:
            entity_id: select.conditional_media
          data:
            option: >
              {{ option }}
