automation: # work around ping integration limitation
  - id: update_ping_wan
    alias: "Ping every 3 minutes"
    trigger:
      - trigger: time_pattern
        minutes: "/3"
    condition: []
    mode: single
    action:
      - action: homeassistant.update_entity
        target:
          entity_id:
            - binary_sensor.ping_dns
            - binary_sensor.ping_google

  - id: update_ping_lan
    alias: "Ping every 1 minute"
    trigger:
      - trigger: time_pattern
        minutes: "/1"
    condition: []
    mode: single
    action:
      - action: homeassistant.update_entity
        target:
          entity_id:
            - binary_sensor.ping_rtr
            - binary_sensor.ping_modem
            - binary_sensor.ping_nas
            - binary_sensor.ping_backup
            #- binary_sensor.ping_printer
            - binary_sensor.ping_ap1
            - binary_sensor.ping_ap2
            - binary_sensor.ping_iot_ap1
            - binary_sensor.ping_iot_ap2
