#binary_sensor:
#  - unique_id: network_ping_rtr
#    name: "Network Ping rtr"
#    platform: ping
#    host: 10.0.1.999
#    count: 1
#
#  - unique_id: network_ping_modem
#    name: "Network Ping modem"
#    platform: ping
#    host: 192.168.100.0
#    count: 1
#
#  - unique_id: network_ping_dns
#    name: "Network Ping DNS"
#    platform: ping
#    host: dns.google
#    count: 1
#
#  - unique_id: network_ping_google
#    name: "Network Ping google"
#    platform: ping
#    host: google.com
#    count: 1

automation: # work around ping integration restrictions
  - id: update_ping_wan
    alias: "Ping every 3 minutes"
    trigger:
      - trigger: time_pattern
        minutes: "/3"
    condition: []
    mode: single
    action:
      - action: homeassistant.update_entity
        target:
          entity_id:
            - binary_sensor.ping_dns
            - binary_sensor.ping_google

  - id: update_ping_lan
    alias: "Ping every 1 minute"
    trigger:
      - trigger: time_pattern
        minutes: "/1"
    condition: []
    mode: single
    action:
      - action: homeassistant.update_entity
        target:
          entity_id:
            - binary_sensor.ping_rtr
            - binary_sensor.ping_modem
            - binary_sensor.ping_nas
            - binary_sensor.ping_backup
            - binary_sensor.ping_printer
            - binary_sensor.ping_ap1
            - binary_sensor.ping_ap2
            - binary_sensor.ping_guest_ap1
            - binary_sensor.ping_guest_ap2

template:
  - binary_sensor:
      - unique_id: network_ping_rtr_problem
        name: "Network Ping rtr Problem"
        icon: mdi:alert
        device_class: problem
        state: >-
          {% set value = states('binary_sensor.ping_rtr') %}
          {% if value != "unavailable" and value != "unknown" %}
          {{    bool(value) == false }}
          {% else %}
          {{     value }}
          {% endif %}

      - unique_id: network_ping_modem_problem
        name: "Network Ping modem Problem"
        icon: mdi:alert
        device_class: problem
        state: >-
          {% set value = states('binary_sensor.ping_modem') %}
          {% if value != "unavailable" and value != "unknown" %}
          {{    bool(value) == false }}
          {% else %}
          {{     value }}
          {% endif %}

      - unique_id: network_ping_dns_problem
        name: "Network Ping DNS Problem"
        icon: mdi:alert
        device_class: problem
        state: >-
          {% set value = states('binary_sensor.ping_dns') %}
          {% if value != "unavailable" and value != "unknown" %}
          {{    bool(value) == false }}
          {% else %}
          {{     value }}
          {% endif %}

      - unique_id: network_ping_google_problem
        name: "Network Ping Google Problem"
        icon: mdi:alert
        device_class: problem
        state: >-
          {% set value = states('binary_sensor.ping_google') %}
          {% if value != "unavailable" and value != "unknown" %}
          {{    bool(value) == false }}
          {% else %}
          {{     value }}
          {% endif %}

      - unique_id: network_ups_problem
        name: "Network UPS Problem"
        icon: mdi:alert
        device_class: problem
        state: >-
          {% set value = states('sensor.ups_status') %}
          {% if value != "unavailable" and value != "unknown" %}
          {{    value != 'Online' }}
          {% else %}
          {{     value }}
          {% endif %}

      - unique_id: network_nas_problem
        name: "Network NAS Problem"
        icon: mdi:alert
        device_class: problem
        state: >-
          {% set value = states('sensor.nas_volume_1_status') %}
          {% if value != "unavailable" and value != "unknown" %}
          {{    value != 'normal' }}
          {% else %}
          {{     value }}
          {% endif %}

      - unique_id: network_backup_problem
        name: "Network Backup Problem"
        icon: mdi:alert
        device_class: problem
        state: >-
          {% set value = states('sensor.backup_volume_1_status') %}
          {% if value != "unavailable" and value != "unknown" %}
          {{    value != 'normal' }}
          {% else %}
          {{     value }}
          {% endif %}

      - unique_id: ups_online
        name: "Network UPS Online"
        device_class: connectivity
        state: >-
          {% set value = states('sensor.ups_status') %}
          {% if value != "unavailable" and value != "unknown" %}
          {{    value == 'Online' }}
          {% else %}
          {{     value }}
          {% endif %}

      - unique_id: cable_modem_online
        name: "Cable Modem Online"
        device_class: connectivity
        state: >-
          {% set value = states('sensor.cable_modem_connection_status') %}
          {% if value != "unavailable" and value != "unknown" %}
          {{    value == 'online' }}
          {% else %}
          {{     value }}
          {% endif %}

  - sensor:
      - unique_id: nr_of_network_problems
        name: "Nr of Network Problems"
        icon: mdi:alert
        state: >-
          {{
              states.binary_sensor | 
              selectattr('entity_id', 'match', 'binary_sensor\.network_.*_problem') |
              selectattr('state', 'eq', 'on') | list | count
          }}

      - unique_id: cable_modem_mean_s_n
        name: "Cable Modem Mean S/N"
        icon: mdi:signal
        state: >-
          {% set data_list = states.sensor | 
                  selectattr('entity_id', 'match', 'sensor\.cable_modem_ds_ch_.*_snr') |
                  map(attribute='state') | map('float', 0) | list %}
          {% set sum_list = data_list | sum %}
          {% set count = data_list | length %}
          {% set mean = sum_list / count %}
          {% set ns = namespace(sum_sq_diffs = 0) %}
          {% for item in data_list %}
          {%     set ns.sum_sq_diffs = ns.sum_sq_diffs + (item - mean)**2 %}
          {% endfor %}
          {% set variance = ns.sum_sq_diffs / count %}
          {% set std_dev = variance**0.5 %}
          {{ (mean | round(1) | string) + " dBmV" + ", σ=" + (std_dev | round(1) | string) }}

      - unique_id: cable_modem_worst_freq
        name: "Cable Modem Worst Freq"
        device_class: frequency
        unit_of_measurement: "MHz"
        state: >-
          {% set value_list = states.sensor | 
                selectattr('entity_id', 'match', 'sensor\.cable_modem_ds_ch_.*_uncorrected') |
                map(attribute='state') | map('float', 0) | list %}
          {% set freq_list = states.sensor | 
                selectattr('entity_id', 'match', 'sensor\.cable_modem_ds_ch_.*_frequency') |
                map(attribute='state') | map('float', 0) | list %}
          {% set highest = max(value_list) %}
          {% set idx = value_list.index(highest) %}
          {{ freq_list[idx] / 1000000.0 }}

  - binary_sensor:
      - unique_id: network_status
        name: "Network Status"
        icon: mdi:alert
        device_class: problem
        state: >-
          {{
              states('sensor.nr_of_network_problems') | int > 0
          }}

device_tracker:
  - platform: ddwrt
    host: 10.1.1.5
    username: !secret ddwrt_uname
    password: !secret ddwrt_passwd
    wireless_only: true

  - platform: ddwrt
    host: 10.1.1.6
    username: !secret ddwrt_uname
    password: !secret ddwrt_passwd
    wireless_only: true
