# OPNpool integration (https://github.com/cvonk/OPNpool)

homeassistant:
  customize:
    sensor.opnpool_pump_power:
      friendly_name: "Pool pump"
      icon: mdi:pump
      unique_id: opnpool_pump_power
      device_class: power

template:
  - sensor:
      - unique_id: opnpool_last_water_temp
        name: "OPNpool Last Water Temp"
        state: "{{ trigger.to_state.state | int }}"
        device_class: "temperature"
        unit_of_measurement: "°F"
        icon: mdi:thermometer-water
        attributes:
          source_sensor: sensor.opnpool_water_temp
    trigger:
      - trigger: state
        entity_id: sensor.opnpool_water_temp
        not_to:
          - "unknown"
          - "unavailable"

  - sensor:
      - unique_id: opnpool_pump_estimated_flow
        name: "OPNpool Pump Estimated Flow"
        device_class: volume_flow_rate
        unit_of_measurement: "gal/min"
        icon: mdi:waves-arrow-right
        state: |
          {% set pump_power = states('sensor.opnpool_pump_power') | float(0) %}
          {% set pump_speed = states("sensor.opnpool_pump_speed") | float(0) %}
          {% if pump_speed > 0 %}
          {{   ((pump_power - (1377 * ((pump_speed)/3450)**3) - 75.3) / (12.5 * ((pump_speed)/3450)**2)) | round(0) }}
          {% else %}
          {{   0 }}
          {% endif %}

      - unique_id: opnpool_pump_estimated_volume
        name: "OPNpool Estimated Volume"
        device_class: volume
        unit_of_measurement: "gal"
        icon: mdi:cup
        state: !secret opnpool_estimated_volume

      - unique_id: opnpool_recommended_runtime
        name: "OPNpool Recommended Runtime"
        unit_of_measurement: h
        icon: mdi:clock-outline
        state: |
          {% set water_temp = states("sensor.opnpool_water_temp") | float(0) %}
          {% if water_temp > 0 %}
          {{   (water_temp / 10) | round(0) }}
          {% else %}
          {{   0 }}
          {% endif %}

      - unique_id: nr_of_pool_warnings
        name: "Nr of pool warnings"
        icon: mdi:alert
        state: |
          {{
            states.binary_sensor | 
            selectattr('entity_id', 'match', 'binary_sensor\.opnpool_.*_warning') |
            selectattr('state', 'eq', 'on') | list | count
          }}

      - unique_id: nr_of_pool_circuits_active
        name: "Nr of Pool Circuits Active"
        icon: mdi:circle-outline
        state: |
          {{ 
              states.switch | 
              selectattr('entity_id', 'match', '^switch\.opnpool_.*_circuit') |
              selectattr('state', 'eq', 'on') | list | count
          }}

  - binary_sensor:
      - unique_id: opnpool_chlor_status_warning
        name: "OPNpool chorinator status warning"
        device_class: problem
        icon: mdi:alert
        state: '{{ states("sensor.opnpool_chlor_status") != "OK" }}'

      - unique_id: opnpool_chlor_salt_warning
        name: "OPNpool chorinator salt warning"
        device_class: problem
        icon: mdi:alert
        state: '{{ states(binary_sensor.opnpool_pump_running) and ((states("sensor.opnpool_chlor_salt")|float(0) < 2700) or (states("sensor.opnpool_chlor_salt")|float(0) > 4500)) }}'

      - unique_id: opnpool_pump_status_warning
        name: "OPNpool pump status problem"
        device_class: problem
        icon: mdi:alert
        state: '{{ states("sensor.opnpool_pump_status") != "OK" }}'

      - unique_id: opnpool_pump_error_warning
        name: "OPNpool pump error warning"
        device_class: problem
        icon: mdi:alert
        state: '{{ states("sensor.opnpool_pump_error")|float(0) != 0 }}'

      - unique_id: pool_chemistry
        name: "Pool chemistry"
        device_class: problem
        icon: mdi:ph
        state: '{{ states("sensor.pool_ph") != "unavailable" }}'

input_boolean:
  # you need to create the corresponding scripts for the logic using 'Toggle switch_entity, with support for spinner' blueprint
  opnpool_pool_circuit_pending:
    name: OPNpool POOL circuit pending
    initial: false
  opnpool_spa_circuit_pending:
    name: OPNpool SPA circuit pending
    initial: false
  opnpool_aux1_circuit_pending:
    name: OPNpool AUX1 circuit pending
    initial: false
  opnpool_aux2_circuit_pending:
    name: OPNpool AUX2 circuit pending
    initial: false

google_assistant:
  entity_config:
    switch.opnpool_pool_circuit:
      name: Circuit
      room: Pool
    switch.opnpool_spa_circuit:
      name: Circuit
      room: Pool
      aliases:
        - Spa
    switch.opnpool_aux1_circuit:
      name: Pump
      room: Pool
    switch.opnpool_aux2_circuit:
      name: Light
      room: Pool
    climate.opnpool_pool_heater:
      name: water
      room: Pool
