# OPNpool integration (https://github.com/cvonk/OPNpool)

homeassistant:
  customize:
    sensor.opnpool_pump_power:
      friendly_name: "Pool pump"
      icon: mdi:pump
      unique_id: opnpool_pump_power
      device_class: power
      unit_of_measurement: "W"
      state_class: measurement
    sensor.opnpool_pump_gpm:
      device_class: volume_flow_rate
      unit_of_measurement: "gal/min"
      state_class: measurement

template:
  - sensor:
      - unique_id: opnpool_last_water_temperature
        name: "OPNpool last water temperature"
        icon: mdi:thermometer-water
        state: "{{ states('sensor.opnpool_water_temp') | int }}"
        device_class: "temperature"
        unit_of_measurement: "°F"
        state_class: measurement
        #attributes:
        #  source_sensor: sensor.opnpool_water_temp
    trigger:
      - trigger: state
        entity_id: sensor.opnpool_water_temp
        not_to:
          - "unknown"
          - "unavailable"

  - sensor:
      - unique_id: opnpool_last_air_temperature
        name: "OPNpool last air temperature"
        state: >-
          {% set value = states('sensor.opnpool_air_temp') %}
          {% if value | is_number %}
          {{    int(value) }}
          {% else %}
          {{     value }}
          {% endif %}
        device_class: "temperature"
        unit_of_measurement: "°F"
        state_class: measurement
        #attributes:
        #  source_sensor: sensor.opnpool_air_temp
    trigger:
      - trigger: state
        entity_id: sensor.opnpool_air_temp
        not_to:
          - "unknown"
          - "unavailable"

input_boolean:
  # requires corresponding scripts for the logic using 'Toggle switch_entity, with support for spinner' blueprint
  opnpool_pool_circuit_pending:
    name: OPNpool POOL circuit pending
    initial: false
  opnpool_spa_circuit_pending:
    name: OPNpool SPA circuit pending
    initial: false
  opnpool_aux1_circuit_pending:
    name: OPNpool AUX1 circuit pending
    initial: false
  opnpool_aux2_circuit_pending:
    name: OPNpool AUX2 circuit pending
    initial: false

  fake_heater: # fake heater so Google Assistant can read the outside temperature
    name: fake_heater
    icon: mdi:toggle-switch-off
    initial: false

climate:
  - unique_id: opnpool_last_air_temperature
    name: "OPNpool outside air"
    platform: generic_thermostat
    heater: input_boolean.fake_heater
    target_sensor: sensor.opnpool_last_air_temperature
    min_temp: 20
    max_temp: 120
